name: Push Release

on:
  pull_request_target:
    types:
      - closed
jobs:
  publish_release:
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true && github.event.pull_request.user.login == 'ds-ragbits-robot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.10"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get tag name
        id: tag_name
        run: |
          echo "::set-output name=new_tag::$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/.*-//')"

      - name: Create release notes
        run: |
          uv run scripts/create_release_notes.py

      - name: Publish release
        run: |
          gh release create v${{ steps.tag_name.outputs.new_tag }} \
            --title v${{ github.event.pull_request.head.ref }}" \
            --notes-file RELEASE_NOTES.md